FROM node:lts

RUN apt-get update && apt-get upgrade -y
RUN apt-get install build-essential -y
RUN apt-get install git -y
RUN apt-get install vim -y

# Install Cloud SDK
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - && apt-get update -y && apt-get install google-cloud-sdk -y

# Configure shell
RUN apt-get install libncurses-dev -y
RUN apt-get install cmake -y
RUN git clone https://github.com/fish-shell/fish-shell.git; cd fish-shell; cmake .; make; make install
RUN rm -r fish-shell
RUN wget https://starship.rs/install.sh
RUN sh install.sh --yes
RUN mkdir -p ~/.config/fish/
RUN echo "starship init fish | source" >> ~/.config/fish/config.fish
RUN git clone https://github.com/SoheilSalmani/config.git; cd config/starship; cp starship.toml ~/.config/
RUN rm -r config
